import { build } from '@caiu/library';

import {
  Player,
  Team,
  League,
  Game,
  Location,
  Stat,
  GameTeam,
  StatCategory,
  TeamStat,
  Players,
  Teams,
  Leagues,
  Locations,
  Games,
  GameTeams,
  GamePlayers,
  Stats,
  TeamStats,
  StatCategories,
  GamePlayer
} from './models';

export const STAT_CATEGORIES = [
  build(StatCategory, { id: 1, name: 'PTS', label: 'Points' }),
  build(StatCategory, { id: 2, name: 'REB', label: 'Rebounds' }),
  build(StatCategory, { id: 3, name: 'AST', label: 'Assists' }),
  build(StatCategory, { id: 4, name: 'BLK', label: 'Blocks' }),
  build(StatCategory, { id: 5, name: 'STL', label: 'Steals' }),
  build(StatCategory, { id: 6, name: 'PF', label: 'Personal Fouls' })
];

export const LEAGUES = [
  build(League, { id: 1, name: '10U' }),
  build(League, { id: 2, name: '12U' }),
  build(League, { id: 3, name: '14U' })
];

export const LOCATIONS = [
  build(Location, { id: 1, name: 'Memorial Park' }),
  build(Location, { id: 2, name: 'Partnership for Better Health' }),
  build(Location, { id: 3, name: 'GB Stuart Foundation' })
];

export const TEAMS = [
  build(Team, {
    id: 1,
    name: 'C-Luv Thrift',
    initials: 'C-Luv',
    color: 'green',
    leagueId: 1,
    headCoachName: 'Latasha'
  }),
  build(Team, {
    id: 2,
    name: 'GB Stuart',
    initials: 'GBS',
    color: 'black',
    leagueId: 1,
    headCoachName: 'Andrew'
  }),
  build(Team, {
    id: 3,
    name: 'Carlisle Home Association',
    initials: 'CHA',
    color: 'red',
    leagueId: 1,
    headCoachName: 'Jamarius'
  }),
  build(Team, {
    id: 4,
    name: 'Cumberland Valley Rising',
    initials: 'CVR',
    color: 'blue',
    leagueId: 1,
    headCoachName: 'Shawn'
  }),
  build(Team, {
    id: 5,
    name: 'Partnership for Better Health',
    initials: 'PBH',
    color: 'yellow',
    leagueId: 1,
    headCoachName: 'Dave H.'
  }),
  build(Team, {
    id: 6,
    name: 'Carlisle Community Coalition',
    initials: 'CCC',
    color: 'deepskyblue',
    leagueId: 1,
    headCoachName: 'Renee'
  }),
  build(Team, {
    id: 7,
    name: 'C-Luv Thrift',
    initials: 'C-Luv',
    color: 'green',
    leagueId: 2,
    headCoachName: 'Kelsey'
  }),
  build(Team, {
    id: 8,
    name: 'GB Stuart Foundation',
    initials: 'GBS',
    color: 'black',
    leagueId: 2,
    headCoachName: 'Andy'
  }),
  build(Team, {
    id: 9,
    name: 'Carlisle Home Association',
    initials: 'CHA',
    color: 'red',
    leagueId: 2,
    headCoachName: 'Dave'
  }),
  build(Team, {
    id: 10,
    name: 'Cumberland Valley Rising',
    initials: 'CVR',
    color: 'blue',
    leagueId: 2,
    headCoachName: 'Walt'
  }),
  build(Team, {
    id: 11,
    name: 'Partnership for Better Health',
    initials: 'PBH',
    color: 'yellow',
    leagueId: 2,
    headCoachName: 'Matt'
  }),
  build(Team, {
    id: 12,
    name: 'C-Luv Thrift',
    initials: 'C-Luv',
    color: 'green',
    leagueId: 3,
    headCoachName: 'Asamara'
  }),
  build(Team, {
    id: 13,
    name: 'GB Stuart Foundation',
    initials: 'GBS',
    color: 'black',
    leagueId: 3,
    headCoachName: 'Zion'
  }),
  build(Team, {
    id: 14,
    name: 'Carlisle Home Association',
    initials: 'CHA',
    color: 'red',
    leagueId: 3,
    headCoachName: 'Doug'
  }),
  build(Team, {
    id: 15,
    name: 'Cumberland Valley Rising',
    initials: 'CVR',
    color: 'blue',
    leagueId: 3,
    headCoachName: 'Ray'
  }),
  build(Team, {
    id: 16,
    name: 'Partnership for Better Health',
    initials: 'PBH',
    color: 'yellow',
    leagueId: 3,
    headCoachName: 'Gary'
  })
];

export const GAMES = [
  build(Game, {
    id: 1,
    startTime: new Date(2019, 6, 25, 17, 30),
    leagueId: 1,
    locationId: 2
  }),
  build(Game, {
    id: 2,
    startTime: new Date(2019, 6, 25, 17, 30),
    leagueId: 1,
    locationId: 3
  }),
  build(Game, {
    id: 3,
    startTime: new Date(2019, 6, 25, 18, 30),
    leagueId: 2,
    locationId: 2
  }),
  build(Game, {
    id: 4,
    startTime: new Date(2019, 6, 25, 18, 30),
    leagueId: 2,
    locationId: 3
  }),
  build(Game, {
    id: 5,
    startTime: new Date(2019, 6, 25, 19, 30),
    leagueId: 3,
    locationId: 2
  }),
  build(Game, {
    id: 6,
    startTime: new Date(2019, 6, 25, 19, 30),
    leagueId: 3,
    locationId: 3
  }),
  build(Game, {
    id: 7,
    startTime: new Date(2019, 6, 27, 17, 30),
    leagueId: 1,
    locationId: 2
  }),
  build(Game, {
    id: 8,
    startTime: new Date(2019, 6, 27, 17, 30),
    leagueId: 1,
    locationId: 3
  }),
  build(Game, {
    id: 9,
    startTime: new Date(2019, 6, 27, 18, 30),
    leagueId: 2,
    locationId: 2
  }),
  build(Game, {
    id: 10,
    startTime: new Date(2019, 6, 27, 18, 30),
    leagueId: 2,
    locationId: 3
  }),
  build(Game, {
    id: 11,
    startTime: new Date(2019, 6, 27, 19, 30),
    leagueId: 3,
    locationId: 2
  }),
  build(Game, {
    id: 12,
    startTime: new Date(2019, 6, 27, 19, 30),
    leagueId: 3,
    locationId: 3
  })
];

export const GAME_TEAMS = [
  build(GameTeam, { id: 1, gameId: 1, teamId: 1 }),
  build(GameTeam, { id: 2, gameId: 1, teamId: 2 }),
  build(GameTeam, { id: 3, gameId: 2, teamId: 3 }),
  build(GameTeam, { id: 4, gameId: 2, teamId: 4 }),
  build(GameTeam, { id: 5, gameId: 3, teamId: 11 }),
  build(GameTeam, { id: 6, gameId: 3, teamId: 10 }),
  build(GameTeam, { id: 7, gameId: 4, teamId: 9 }),
  build(GameTeam, { id: 8, gameId: 4, teamId: 8 }),
  build(GameTeam, { id: 9, gameId: 5, teamId: 12 }),
  build(GameTeam, { id: 10, gameId: 5, teamId: 14 }),
  build(GameTeam, { id: 11, gameId: 6, teamId: 16 }),
  build(GameTeam, { id: 12, gameId: 6, teamId: 13 }),
  build(GameTeam, { id: 13, gameId: 7, teamId: 5 }),
  build(GameTeam, { id: 14, gameId: 7, teamId: 6 }),
  build(GameTeam, { id: 15, gameId: 8, teamId: 1 }),
  build(GameTeam, { id: 16, gameId: 8, teamId: 3 }),
  build(GameTeam, { id: 17, gameId: 9, teamId: 7 }),
  build(GameTeam, { id: 18, gameId: 9, teamId: 9 }),
  build(GameTeam, { id: 19, gameId: 10, teamId: 11 }),
  build(GameTeam, { id: 20, gameId: 10, teamId: 8 }),
  build(GameTeam, { id: 21, gameId: 11, teamId: 16 }),
  build(GameTeam, { id: 22, gameId: 11, teamId: 12 }),
  build(GameTeam, { id: 23, gameId: 12, teamId: 13 }),
  build(GameTeam, { id: 24, gameId: 12, teamId: 15 })
];

export const TEAM_STATS = [
  build(TeamStat, { gameTeamId: 1, statCategoryId: 1, total: 27 }),
  build(TeamStat, { gameTeamId: 2, statCategoryId: 1, total: 12 }),
  build(TeamStat, { gameTeamId: 3, statCategoryId: 1, total: 21 }),
  build(TeamStat, { gameTeamId: 4, statCategoryId: 1, total: 18 }),
  build(TeamStat, { gameTeamId: 5, statCategoryId: 1, total: 12 }),
  build(TeamStat, { gameTeamId: 6, statCategoryId: 1, total: 58 }),
  build(TeamStat, { gameTeamId: 7, statCategoryId: 1, total: 46 }),
  build(TeamStat, { gameTeamId: 8, statCategoryId: 1, total: 10 }),
  build(TeamStat, { gameTeamId: 9, statCategoryId: 1, total: 62 }),
  build(TeamStat, { gameTeamId: 10, statCategoryId: 1, total: 57 }),
  build(TeamStat, { gameTeamId: 11, statCategoryId: 1, total: 94 }),
  build(TeamStat, { gameTeamId: 12, statCategoryId: 1, total: 62 }),
  build(TeamStat, { gameTeamId: 13, statCategoryId: 1, total: 10 }),
  build(TeamStat, { gameTeamId: 14, statCategoryId: 1, total: 30 }),
  build(TeamStat, { gameTeamId: 15, statCategoryId: 1, total: 16 }),
  build(TeamStat, { gameTeamId: 16, statCategoryId: 1, total: 21 }),
  build(TeamStat, { gameTeamId: 17, statCategoryId: 1, total: 30 }),
  build(TeamStat, { gameTeamId: 18, statCategoryId: 1, total: 56 }),
  build(TeamStat, { gameTeamId: 19, statCategoryId: 1, total: 28 }),
  build(TeamStat, { gameTeamId: 20, statCategoryId: 1, total: 40 }),
  build(TeamStat, { gameTeamId: 21, statCategoryId: 1, total: 106 }),
  build(TeamStat, { gameTeamId: 22, statCategoryId: 1, total: 76 }),
  build(TeamStat, { gameTeamId: 23, statCategoryId: 1, total: 75 }),
  build(TeamStat, { gameTeamId: 24, statCategoryId: 1, total: 38 })
];

export const PLAYERS = [
  build(Player, { id: 0, firstName: '', lastName: '' }),
  build(Player, { id: 1, firstName: 'Damauri', lastName: 'Thomas' }),
  build(Player, { id: 2, firstName: 'Drake', lastName: 'Kelley' }),
  build(Player, { id: 3, firstName: 'Javoni', lastName: 'Porter' }),
  build(Player, { id: 4, firstName: 'Isaiah', lastName: 'Ream' }),
  build(Player, {
    id: 5,
    firstName: 'Kaleb',
    lastName: 'Mjuholland',
    isActive: false
  }),
  build(Player, { id: 6, firstName: 'Jadon', lastName: 'Kipp' }),
  build(Player, { id: 7, firstName: 'Jace', lastName: 'Roth' }),
  build(Player, { id: 8, firstName: 'Tayah', lastName: 'Felton' }),
  build(Player, { id: 9, firstName: "T'oure", lastName: 'Evans' }),
  build(Player, { id: 10, firstName: 'Wesley', lastName: 'Heckman' }),
  build(Player, { id: 11, firstName: 'Khadr', lastName: 'Vasser' }),
  build(Player, { id: 12, firstName: 'Austin', lastName: 'Marshall' }),
  build(Player, {
    id: 13,
    firstName: 'Amari',
    lastName: 'Ibrahim',
    isActive: false
  }),
  build(Player, { id: 14, firstName: 'Summer', lastName: 'Kunza' }),
  build(Player, { id: 15, firstName: 'Carter', lastName: 'Wilson' }),
  build(Player, { id: 16, firstName: 'Jayde', lastName: 'Wilson' }),
  build(Player, {
    id: 17,
    firstName: 'Chester',
    lastName: 'Wilson',
    nickname: 'CJ'
  }),
  build(Player, { id: 18, firstName: 'Sean', lastName: 'Smith' }),
  build(Player, { id: 19, firstName: 'Azmina', lastName: 'Palmer' }),
  build(Player, { id: 20, firstName: 'Trevon', lastName: 'Harris' }),
  build(Player, { id: 21, firstName: 'Xzavier', lastName: 'Tatum' }),
  build(Player, { id: 22, firstName: 'Eisley', lastName: 'Seretti' }),
  build(Player, { id: 23, firstName: 'Jack', lastName: 'Becket' }),
  build(Player, { id: 24, firstName: 'Jace', lastName: 'Dagaetano' }),
  build(Player, { id: 25, firstName: 'Bishop', lastName: 'Campbell' }),
  build(Player, { id: 26, firstName: 'Gus', lastName: 'Yarnell' }),
  build(Player, { id: 27, firstName: 'Sadie', lastName: 'McMeekin' }),
  build(Player, { id: 28, firstName: 'Isla', lastName: 'Heckman' }),
  build(Player, { id: 29, firstName: 'Connor', lastName: 'Rutz' }),
  build(Player, { id: 30, firstName: 'Khalil', lastName: 'Jackson' }),
  build(Player, { id: 31, firstName: 'Channing', lastName: 'Coon' }),
  build(Player, { id: 32, firstName: 'Sincere', lastName: 'Ewell' }),
  build(Player, { id: 33, firstName: 'Grant', lastName: 'Vitek' }),
  build(Player, {
    id: 34,
    firstName: 'Adelyn',
    lastName: 'Pagze',
    isActive: false
  }),
  build(Player, { id: 35, firstName: 'Sinclair', lastName: 'Ewell' }),
  build(Player, { id: 36, firstName: 'Nasir', lastName: 'Saric' }),
  build(Player, { id: 37, firstName: 'Lukas', lastName: 'Wright' }),
  build(Player, { id: 38, firstName: 'Roma', lastName: 'Dizon' }),
  build(Player, { id: 39, firstName: 'Jasper', lastName: 'Brinkley' }),
  build(Player, { id: 40, firstName: 'Isaac', lastName: 'Kimmel' }),
  build(Player, {
    id: 41,
    firstName: 'Rylee',
    lastName: 'Blair',
    isActive: false
  }),
  build(Player, {
    id: 42,
    firstName: 'Caleb',
    lastName: 'Pagze',
    isActive: false
  }),
  build(Player, { id: 43, firstName: 'Kenyon', lastName: 'Wideny' }),
  build(Player, { id: 44, firstName: 'JJ', lastName: 'Fenner' }),
  build(Player, { id: 45, firstName: 'Kenzo', lastName: 'Veron' }),
  build(Player, { id: 46, firstName: 'Millio', lastName: 'Millz' }),
  build(Player, { id: 47, firstName: 'Preson', lastName: 'Stackfield' }),
  build(Player, { id: 48, firstName: 'Quentin', lastName: 'Stackfield' }),
  build(Player, { id: 49, firstName: 'Zion', lastName: 'Thomas' }),
  build(Player, {
    id: 50,
    firstName: 'Jenavive',
    lastName: 'Thomas',
    isActive: false
  }),
  build(Player, {
    id: 51,
    firstName: 'Taliyah',
    lastName: 'Robinson',
    isActive: false
  }),
  build(Player, { id: 52, firstName: 'Isaiah', lastName: 'Robinson' }),
  build(Player, {
    id: 53,
    firstName: 'Avah',
    lastName: 'Thorson',
    isActive: false
  }),
  build(Player, {
    id: 54,
    firstName: 'Jacob',
    lastName: 'Weidner',
    isActive: false
  }),
  build(Player, {
    id: 55,
    firstName: 'Malachai',
    lastName: 'Weidner',
    isActive: false
  }),
  build(Player, { id: 56, firstName: 'Luke', lastName: 'Fischer' }),
  build(Player, { id: 57, firstName: 'Xavier', lastName: 'Campbell' }),
  build(Player, { id: 58, firstName: 'Kolbin', lastName: 'Heberling' }),
  build(Player, { id: 59, firstName: 'Tayshaun', lastName: 'Dave' }),
  build(Player, { id: 60, firstName: 'Connor', lastName: 'Baldwin' }),
  build(Player, { id: 61, firstName: 'Sidney', lastName: 'Ewell' }),
  build(Player, { id: 62, firstName: 'Aiden', lastName: 'Dobyns' }),
  build(Player, { id: 63, firstName: 'Gennaro', lastName: 'Pensa' }),
  build(Player, { id: 64, firstName: 'Dominic', lastName: 'Johnson' }),
  build(Player, { id: 65, firstName: 'Austin', lastName: 'Reichard' }),
  build(Player, { id: 66, firstName: "Z'varione", lastName: 'Clarke' }),
  build(Player, { id: 67, firstName: 'Ashton', lastName: 'Coon' }),
  build(Player, { id: 68, firstName: 'Jadon', lastName: 'Harris' }),
  build(Player, { id: 69, firstName: 'Trent', lastName: 'Keeler' }),
  build(Player, { id: 70, firstName: 'Josh', lastName: 'Kendall' }),
  build(Player, { id: 71, firstName: 'Jahmiel', lastName: 'Harrel' }),
  build(Player, { id: 72, firstName: 'Kazmeer', lastName: 'Jaquez' }),
  build(Player, { id: 73, firstName: 'Danielle', lastName: 'Klinger' }),
  build(Player, { id: 74, firstName: 'Jasmine', lastName: 'Rouvre' }),
  build(Player, { id: 75, firstName: 'Jaquez', lastName: 'Knight' }),
  build(Player, { id: 76, firstName: 'Cayson', lastName: 'Johnson' }),
  build(Player, { id: 77, firstName: 'Julian', lastName: 'Miller' }),
  build(Player, { id: 78, firstName: 'Angelo', lastName: 'Bartolli' }),
  build(Player, { id: 79, firstName: 'Malachai', lastName: 'Thomas' }),
  build(Player, { id: 80, firstName: 'DJ', lastName: 'Thomas' }),
  build(Player, {
    id: 81,
    firstName: 'Alaina',
    lastName: 'Sweet',
    isActive: false
  }),
  build(Player, { id: 82, firstName: "C'myirh", lastName: 'Thomas-Hodge' }),
  build(Player, { id: 83, firstName: 'Alex', lastName: 'Pida' }),
  build(Player, { id: 84, firstName: 'Erik', lastName: 'Samuelson' }),
  build(Player, { id: 85, firstName: 'Tavien', lastName: 'Pham' }),
  build(Player, { id: 86, firstName: 'Andrew', lastName: 'Bartolli' }),
  build(Player, { id: 87, firstName: 'Vincent', lastName: 'Kunza' }),
  build(Player, { id: 88, firstName: 'Braylon', lastName: 'Shugart' }),
  build(Player, {
    id: 89,
    firstName: 'Tahjmere',
    lastName: 'Williams',
    isActive: false
  }),
  build(Player, { id: 90, firstName: 'Henry', lastName: 'Boegel' }),
  build(Player, { id: 91, firstName: 'Jordan', lastName: 'McGowan' }),
  build(Player, { id: 92, firstName: 'Kamora', lastName: 'Johnson' }),
  build(Player, { id: 93, firstName: 'Nolan', lastName: 'Snyder' }),
  build(Player, { id: 94, firstName: 'Masyn', lastName: 'McMeekin' }),
  build(Player, { id: 95, firstName: 'Spencer', lastName: 'Griffie' }),
  build(Player, { id: 96, firstName: 'Conway', lastName: 'Brown' }),
  build(Player, { id: 97, firstName: 'Lucas', lastName: 'Ream' }),
  build(Player, { id: 98, firstName: 'Branden', lastName: 'Felton' }),
  build(Player, { id: 99, firstName: 'Damion', lastName: 'Jones' }),
  build(Player, { id: 100, firstName: 'Skyla', lastName: 'Hancock' }),
  build(Player, { id: 101, firstName: 'Jacob', lastName: 'Goldsborough' }),
  build(Player, { id: 102, firstName: 'Ethan', lastName: 'Yentzer' }),
  build(Player, { id: 103, firstName: 'Geo', lastName: 'Villanueva' }),
  build(Player, { id: 104, firstName: 'Joeseph', lastName: 'Rosado' }),
  build(Player, { id: 105, firstName: 'Tyreke', lastName: 'Flowers' }),
  build(Player, { id: 106, firstName: 'Jaden', lastName: 'Pham' }),
  build(Player, { id: 107, firstName: 'Avery', lastName: 'Stanback' }),
  build(Player, { id: 108, firstName: 'Damon', lastName: 'Thomas' }),
  build(Player, { id: 109, firstName: 'Nassir', lastName: 'Palmer' }),
  build(Player, { id: 110, firstName: 'Brayden', lastName: 'Lindsey' }),
  build(Player, { id: 111, firstName: 'Julian', lastName: 'Christopher' }),
  build(Player, { id: 112, firstName: 'Devon', lastName: 'Montgomery' }),
  build(Player, { id: 113, firstName: 'Jeremiah', lastName: 'Snyder' }),
  build(Player, { id: 114, firstName: 'Jaquise', lastName: 'Morrell' }),
  build(Player, { id: 115, firstName: 'Bryson', lastName: 'Williams' }),
  build(Player, { id: 116, firstName: 'Jaiden', lastName: 'Bass' }),
  build(Player, { id: 117, firstName: 'Javoni', lastName: 'Mosesly' }),
  build(Player, {
    id: 118,
    firstName: 'Dewitt',
    lastName: 'Smith',
    isActive: false
  }),
  build(Player, { id: 119, firstName: 'Jeremih', lastName: 'Sothers' }),
  build(Player, { id: 120, firstName: 'Kareem', lastName: 'Lawson' }),
  build(Player, { id: 121, firstName: 'Quamari', lastName: 'Vasser' }),
  build(Player, { id: 122, firstName: 'Jaydon', lastName: 'Smith' }),
  build(Player, { id: 123, firstName: 'Tionne', lastName: 'Johnson' }),
  build(Player, { id: 124, firstName: 'Marquise', lastName: 'Miller' }),
  build(Player, { id: 125, firstName: 'Anthony', lastName: 'Bartolli' }),
  build(Player, { id: 126, firstName: 'Maxwell', lastName: 'Spraglin' }),
  build(Player, { id: 127, firstName: 'Khaleed', lastName: 'Washington' }),
  build(Player, { id: 128, firstName: 'Jayden', lastName: 'Wright' }),
  build(Player, { id: 129, firstName: 'Jess', lastName: 'Rouvre' }),
  build(Player, { id: 130, firstName: 'Daymion', lastName: 'Scott' }),
  build(Player, { id: 131, firstName: 'Eli', lastName: 'Kimmel' }),
  build(Player, { id: 132, firstName: 'Jacob', lastName: 'Heckman' }),
  build(Player, {
    id: 133,
    firstName: 'Silah',
    lastName: 'Niertako',
    isActive: false
  }),
  build(Player, { id: 134, firstName: 'Mekhar', lastName: 'McBrid' }),
  build(Player, { id: 135, firstName: 'Ian', lastName: 'Messano' }),
  build(Player, { id: 136, firstName: 'Dominic', lastName: 'Roman' }),
  build(Player, {
    id: 137,
    firstName: 'Parker',
    lastName: 'Smith',
    isActive: false
  }),
  build(Player, { id: 138, firstName: 'Jeremiah', lastName: 'Seller' }),
  build(Player, { id: 139, firstName: 'EZ', lastName: 'Thomas' }),
  build(Player, { id: 140, firstName: 'Luke', lastName: 'August' }),
  build(Player, { id: 141, firstName: 'Louie', lastName: 'Shank' }),
  build(Player, { id: 142, firstName: 'Eli', lastName: 'Hargrove' }),
  build(Player, { id: 143, firstName: 'Hunter', lastName: 'Finkenbinder' }),
  build(Player, { id: 144, firstName: 'Jeremiah', lastName: 'Hargrove' }),
  build(Player, { id: 145, firstName: 'Jose', lastName: 'Oaks' }),
  build(Player, { id: 146, firstName: 'Justus', lastName: 'Johnson' }),
  build(Player, { id: 147, firstName: 'Jake', lastName: 'Panko' }),
  build(Player, { id: 148, firstName: 'Jasier', lastName: 'Brinkley' }), // C-Luv
  build(Player, { id: 149, firstName: 'Dominic', lastName: 'Bowman' }), // GBS
  build(Player, { id: 150, firstName: 'Sean', lastName: 'Scott' }), // PBH
  build(Player, { id: 151, firstName: 'Khamdyn', lastName: 'Drew' }), // CCC
  build(Player, { id: 152, firstName: 'Zach', lastName: 'Goldsborough' }), // CCC
  build(Player, { id: 153, firstName: 'Brayon', lastName: 'Hunter' }), // CCC
  build(Player, { id: 154, firstName: 'Angelique', lastName: 'Noia' }), // CVR
  build(Player, { id: 155, firstName: 'Dennis', lastName: 'Jones' }), // CVR
  build(Player, { id: 156, firstName: 'Lucas', lastName: 'Smith' }), // GBS
  build(Player, { id: 157, firstName: 'Joaquin', lastName: 'Ortiz' }), // PBH
  build(Player, { id: 158, firstName: 'Landon', lastName: 'Lackemeyer' }), // C-Luv
  build(Player, { id: 159, firstName: 'Anthony', lastName: 'Smith' }), // C-Luv
  build(Player, { id: 160, firstName: 'Adrian', lastName: 'Bennett' }), // CVR
  build(Player, { id: 161, firstName: 'Brian', lastName: 'Szeles' }), // CVR
  build(Player, { id: 162, firstName: 'Nadia', lastName: 'Hunter' }), // 12U - CVR
  build(Player, { id: 163, firstName: 'Jace', lastName: 'Jones' })
];

export const GAME_PLAYERS = [
  build(GamePlayer, { id: 1, gameTeamId: 1, playerId: 7, jerseyNumber: '0' }),
  build(GamePlayer, { id: 2, gameTeamId: 1, playerId: 6, jerseyNumber: '1' }),
  build(GamePlayer, { id: 3, gameTeamId: 1, playerId: 1, jerseyNumber: '2' }),
  build(GamePlayer, { id: 4, gameTeamId: 1, playerId: 3, jerseyNumber: '3' }),
  build(GamePlayer, { id: 5, gameTeamId: 1, playerId: 2, jerseyNumber: '4' }),
  build(GamePlayer, { id: 6, gameTeamId: 1, playerId: 8, jerseyNumber: '6' }),
  build(GamePlayer, { id: 7, gameTeamId: 1, playerId: 10, jerseyNumber: '9' }),
  build(GamePlayer, { id: 8, gameTeamId: 1, playerId: 0, jerseyNumber: '10' }),
  build(GamePlayer, { id: 9, gameTeamId: 2, playerId: 0, jerseyNumber: '0' }),
  build(GamePlayer, { id: 10, gameTeamId: 2, playerId: 17, jerseyNumber: '2' }),
  build(GamePlayer, { id: 11, gameTeamId: 2, playerId: 12, jerseyNumber: '3' }),
  build(GamePlayer, { id: 12, gameTeamId: 2, playerId: 0, jerseyNumber: '5' }),
  build(GamePlayer, { id: 13, gameTeamId: 2, playerId: 0, jerseyNumber: '8' }),
  build(GamePlayer, { id: 14, gameTeamId: 2, playerId: 15, jerseyNumber: '9' }),
  build(GamePlayer, { id: 15, gameTeamId: 2, playerId: 16, jerseyNumber: '10' }),
  build(GamePlayer, { id: 16, gameTeamId: 2, playerId: 0, jerseyNumber: '11' }),
  build(GamePlayer, { id: 17, gameTeamId: 3, playerId: 22, jerseyNumber: '0' }),
  build(GamePlayer, { id: 18, gameTeamId: 3, playerId: 20, jerseyNumber: '1' }),
  build(GamePlayer, { id: 19, gameTeamId: 3, playerId: 28, jerseyNumber: '2' }),
  build(GamePlayer, { id: 20, gameTeamId: 3, playerId: 27, jerseyNumber: '6' }),
  build(GamePlayer, { id: 21, gameTeamId: 3, playerId: 25, jerseyNumber: '7' }),
  build(GamePlayer, { id: 22, gameTeamId: 3, playerId: 26, jerseyNumber: '8' }),
  build(GamePlayer, { id: 23, gameTeamId: 3, playerId: 24, jerseyNumber: '9' }),
  build(GamePlayer, { id: 24, gameTeamId: 3, playerId: 23, jerseyNumber: '10' }),
  build(GamePlayer, { id: 25, gameTeamId: 4, playerId: 37, jerseyNumber: '3' }),
  build(GamePlayer, { id: 26, gameTeamId: 4, playerId: 29, jerseyNumber: '7' }),
  build(GamePlayer, { id: 27, gameTeamId: 4, playerId: 30, jerseyNumber: '8' }),
  build(GamePlayer, { id: 28, gameTeamId: 4, playerId: 36, jerseyNumber: '10' }),
  build(GamePlayer, { id: 29, gameTeamId: 5, playerId: 72, jerseyNumber: '0' }),
  build(GamePlayer, { id: 30, gameTeamId: 5, playerId: 67, jerseyNumber: '1' }),
  build(GamePlayer, { id: 31, gameTeamId: 5, playerId: 66, jerseyNumber: '2' }),
  build(GamePlayer, { id: 32, gameTeamId: 5, playerId: 71, jerseyNumber: '4' }),
  build(GamePlayer, { id: 33, gameTeamId: 5, playerId: 65, jerseyNumber: '5' }),
  build(GamePlayer, { id: 34, gameTeamId: 5, playerId: 68, jerseyNumber: '7' }),
  build(GamePlayer, { id: 35, gameTeamId: 5, playerId: 70, jerseyNumber: '7' }),
  build(GamePlayer, { id: 36, gameTeamId: 5, playerId: 74, jerseyNumber: '9' }),
  build(GamePlayer, { id: 37, gameTeamId: 6, playerId: 83, jerseyNumber: '0' }),
  build(GamePlayer, { id: 38, gameTeamId: 6, playerId: 79, jerseyNumber: '1' }),
  build(GamePlayer, { id: 39, gameTeamId: 6, playerId: 77, jerseyNumber: '2' }),
  build(GamePlayer, { id: 40, gameTeamId: 6, playerId: 76, jerseyNumber: '3' }),
  build(GamePlayer, { id: 41, gameTeamId: 6, playerId: 155, jerseyNumber: '5' }),
  build(GamePlayer, { id: 42, gameTeamId: 6, playerId: 75, jerseyNumber: '6' }),
  build(GamePlayer, { id: 43, gameTeamId: 6, playerId: 82, jerseyNumber: '8' }),
  build(GamePlayer, { id: 44, gameTeamId: 7, playerId: 100, jerseyNumber: '0' }),
  build(GamePlayer, { id: 45, gameTeamId: 7, playerId: 163, jerseyNumber: '1' }),
  build(GamePlayer, { id: 46, gameTeamId: 7, playerId: 101, jerseyNumber: '2' }),
  build(GamePlayer, { id: 47, gameTeamId: 7, playerId: 102, jerseyNumber: '3' }),
  build(GamePlayer, { id: 48, gameTeamId: 7, playerId: 96, jerseyNumber: '4' }),
  build(GamePlayer, { id: 49, gameTeamId: 7, playerId: 162, jerseyNumber: '5' }),
  build(GamePlayer, { id: 50, gameTeamId: 7, playerId: 94, jerseyNumber: '6' }),
  build(GamePlayer, { id: 51, gameTeamId: 7, playerId: 98, jerseyNumber: '7' }),
  build(GamePlayer, { id: 52, gameTeamId: 7, playerId: 97, jerseyNumber: '8' }),
  build(GamePlayer, { id: 53, gameTeamId: 8, playerId: 88, jerseyNumber: '0' }),
  build(GamePlayer, { id: 54, gameTeamId: 8, playerId: 90, jerseyNumber: '4' }),
  build(GamePlayer, { id: 55, gameTeamId: 8, playerId: 93, jerseyNumber: '7' }),
  build(GamePlayer, { id: 56, gameTeamId: 8, playerId: 84, jerseyNumber: '8' }),
  build(GamePlayer, { id: 57, gameTeamId: 9, playerId: 124, jerseyNumber: '0' }),
  build(GamePlayer, { id: 58, gameTeamId: 9, playerId: 127, jerseyNumber: '1' }),
  build(GamePlayer, { id: 59, gameTeamId: 9, playerId: 158, jerseyNumber: '3' }),
  build(GamePlayer, { id: 60, gameTeamId: 9, playerId: 159, jerseyNumber: '4' }),
  build(GamePlayer, { id: 61, gameTeamId: 9, playerId: 129, jerseyNumber: '5' }),
  build(GamePlayer, { id: 62, gameTeamId: 9, playerId: 123, jerseyNumber: '6' }),
  build(GamePlayer, { id: 63, gameTeamId: 9, playerId: 126, jerseyNumber: '7' }),
  build(GamePlayer, { id: 64, gameTeamId: 9, playerId: 122, jerseyNumber: '8' }),
  build(GamePlayer, { id: 65, gameTeamId: 9, playerId: 124, jerseyNumber: '9' }),
  build(GamePlayer, { id: 66, gameTeamId: 10, playerId: 143, jerseyNumber: '0' }),
  build(GamePlayer, { id: 67, gameTeamId: 10, playerId: 147, jerseyNumber: '1' }),
  build(GamePlayer, { id: 68, gameTeamId: 10, playerId: 140, jerseyNumber: '3' }),
  build(GamePlayer, { id: 69, gameTeamId: 10, playerId: 139, jerseyNumber: '4' }),
  build(GamePlayer, { id: 70, gameTeamId: 10, playerId: 146, jerseyNumber: '4' }),
  build(GamePlayer, { id: 71, gameTeamId: 10, playerId: 142, jerseyNumber: '7' }),
  build(GamePlayer, { id: 72, gameTeamId: 10, playerId: 141, jerseyNumber: '8' }),
  build(GamePlayer, { id: 73, gameTeamId: 11, playerId: 116, jerseyNumber: '0' }),
  build(GamePlayer, { id: 74, gameTeamId: 11, playerId: 157, jerseyNumber: '1' }),
  build(GamePlayer, { id: 75, gameTeamId: 11, playerId: 117, jerseyNumber: '2' }),
  build(GamePlayer, { id: 76, gameTeamId: 11, playerId: 113, jerseyNumber: '3' }),
  build(GamePlayer, { id: 77, gameTeamId: 11, playerId: 115, jerseyNumber: '4' }),
  build(GamePlayer, { id: 78, gameTeamId: 11, playerId: 120, jerseyNumber: '5' }),
  build(GamePlayer, { id: 79, gameTeamId: 11, playerId: 112, jerseyNumber: '8' }),
  build(GamePlayer, { id: 80, gameTeamId: 11, playerId: 114, jerseyNumber: '9' }),
  build(GamePlayer, { id: 81, gameTeamId: 12, playerId: 107, jerseyNumber: '0' }),
  build(GamePlayer, { id: 82, gameTeamId: 12, playerId: 109, jerseyNumber: '1' }),
  build(GamePlayer, { id: 83, gameTeamId: 12, playerId: 105, jerseyNumber: '3' }),
  build(GamePlayer, { id: 84, gameTeamId: 12, playerId: 111, jerseyNumber: '4' }),
  build(GamePlayer, { id: 85, gameTeamId: 12, playerId: 104, jerseyNumber: '5' }),
  build(GamePlayer, { id: 86, gameTeamId: 12, playerId: 80, jerseyNumber: '6' }),
  build(GamePlayer, { id: 87, gameTeamId: 12, playerId: 106, jerseyNumber: '8' }),
  build(GamePlayer, { id: 88, gameTeamId: 13, playerId: 46, jerseyNumber: '0' }),
  build(GamePlayer, { id: 89, gameTeamId: 13, playerId: 40, jerseyNumber: '5' }),
  build(GamePlayer, { id: 90, gameTeamId: 13, playerId: 0, jerseyNumber: '6' }),
  build(GamePlayer, { id: 91, gameTeamId: 13, playerId: 45, jerseyNumber: '10' }),
  build(GamePlayer, { id: 92, gameTeamId: 14, playerId: 48, jerseyNumber: '0' }),
  build(GamePlayer, { id: 93, gameTeamId: 14, playerId: 49, jerseyNumber: '2' }),
  build(GamePlayer, { id: 94, gameTeamId: 14, playerId: 9, jerseyNumber: '3' }),
  build(GamePlayer, { id: 95, gameTeamId: 14, playerId: 153, jerseyNumber: '5' }),
  build(GamePlayer, { id: 96, gameTeamId: 14, playerId: 47, jerseyNumber: '6' }),
  build(GamePlayer, { id: 97, gameTeamId: 14, playerId: 52, jerseyNumber: '7' }),
  build(GamePlayer, { id: 98, gameTeamId: 14, playerId: 151, jerseyNumber: '8' }),
  build(GamePlayer, { id: 99, gameTeamId: 15, playerId: 7, jerseyNumber: '0' }),
  build(GamePlayer, { id: 100, gameTeamId: 15, playerId: 6, jerseyNumber: '1' }),
  build(GamePlayer, { id: 101, gameTeamId: 15, playerId: 1, jerseyNumber: '2' }),
  build(GamePlayer, { id: 102, gameTeamId: 15, playerId: 3, jerseyNumber: '3' }),
  build(GamePlayer, { id: 103, gameTeamId: 15, playerId: 2, jerseyNumber: '4' }),
  build(GamePlayer, { id: 104, gameTeamId: 15, playerId: 8, jerseyNumber: '6' }),
  build(GamePlayer, { id: 105, gameTeamId: 15, playerId: 10, jerseyNumber: '9' }),
  build(GamePlayer, { id: 106, gameTeamId: 16, playerId: 22, jerseyNumber: '0' }),
  build(GamePlayer, { id: 107, gameTeamId: 16, playerId: 20, jerseyNumber: '1' }),
  build(GamePlayer, { id: 108, gameTeamId: 16, playerId: 28, jerseyNumber: '2' }),
  build(GamePlayer, { id: 109, gameTeamId: 16, playerId: 27, jerseyNumber: '6' }),
  build(GamePlayer, { id: 110, gameTeamId: 16, playerId: 25, jerseyNumber: '7' }),
  build(GamePlayer, { id: 111, gameTeamId: 16, playerId: 26, jerseyNumber: '8' }),
  build(GamePlayer, { id: 112, gameTeamId: 16, playerId: 24, jerseyNumber: '9' }),
  build(GamePlayer, {
    id: 113,
    gameTeamId: 16,
    playerId: 23,
    jerseyNumber: '10'
  }),
  build(GamePlayer, { id: 114, gameTeamId: 17, playerId: 59, jerseyNumber: '0' }),
  build(GamePlayer, { id: 115, gameTeamId: 17, playerId: 56, jerseyNumber: '1' }),
  build(GamePlayer, { id: 116, gameTeamId: 17, playerId: 58, jerseyNumber: '3' }),
  build(GamePlayer, { id: 117, gameTeamId: 17, playerId: 62, jerseyNumber: '7' }),
  build(GamePlayer, { id: 118, gameTeamId: 17, playerId: 61, jerseyNumber: '8' }),
  build(GamePlayer, { id: 119, gameTeamId: 18, playerId: 22, jerseyNumber: '0' }),
  build(GamePlayer, { id: 120, gameTeamId: 18, playerId: 20, jerseyNumber: '1' }),
  build(GamePlayer, {
    id: 121,
    gameTeamId: 18,
    playerId: 102,
    jerseyNumber: '3'
  }),
  build(GamePlayer, { id: 122, gameTeamId: 18, playerId: 96, jerseyNumber: '4' }),
  build(GamePlayer, { id: 123, gameTeamId: 18, playerId: 27, jerseyNumber: '6' }),
  build(GamePlayer, { id: 124, gameTeamId: 18, playerId: 25, jerseyNumber: '7' }),
  build(GamePlayer, { id: 125, gameTeamId: 19, playerId: 72, jerseyNumber: '0' }),
  build(GamePlayer, { id: 126, gameTeamId: 19, playerId: 67, jerseyNumber: '1' }),
  build(GamePlayer, { id: 127, gameTeamId: 19, playerId: 66, jerseyNumber: '2' }),
  build(GamePlayer, { id: 128, gameTeamId: 19, playerId: 73, jerseyNumber: '3' }),
  build(GamePlayer, { id: 129, gameTeamId: 19, playerId: 65, jerseyNumber: '5' }),
  build(GamePlayer, { id: 130, gameTeamId: 19, playerId: 68, jerseyNumber: '7' }),
  build(GamePlayer, { id: 131, gameTeamId: 19, playerId: 70, jerseyNumber: '7' }),
  build(GamePlayer, { id: 132, gameTeamId: 19, playerId: 74, jerseyNumber: '9' }),
  build(GamePlayer, { id: 133, gameTeamId: 20, playerId: 88, jerseyNumber: '0' }),
  build(GamePlayer, { id: 134, gameTeamId: 20, playerId: 66, jerseyNumber: '2' }),
  build(GamePlayer, { id: 135, gameTeamId: 20, playerId: 90, jerseyNumber: '4' }),
  build(GamePlayer, { id: 136, gameTeamId: 20, playerId: 65, jerseyNumber: '5' }),
  build(GamePlayer, { id: 137, gameTeamId: 20, playerId: 93, jerseyNumber: '7' }),
  build(GamePlayer, { id: 138, gameTeamId: 20, playerId: 84, jerseyNumber: '8' }),
  build(GamePlayer, { id: 139, gameTeamId: 20, playerId: 91, jerseyNumber: '9' }),
  build(GamePlayer, {
    id: 140,
    gameTeamId: 20,
    playerId: 156,
    jerseyNumber: '9'
  }),
  build(GamePlayer, {
    id: 141,
    gameTeamId: 21,
    playerId: 116,
    jerseyNumber: '0'
  }),
  build(GamePlayer, {
    id: 142,
    gameTeamId: 21,
    playerId: 157,
    jerseyNumber: '1'
  }),
  build(GamePlayer, {
    id: 143,
    gameTeamId: 21,
    playerId: 117,
    jerseyNumber: '2'
  }),
  build(GamePlayer, {
    id: 144,
    gameTeamId: 21,
    playerId: 113,
    jerseyNumber: '3'
  }),
  build(GamePlayer, {
    id: 145,
    gameTeamId: 21,
    playerId: 115,
    jerseyNumber: '4'
  }),
  build(GamePlayer, {
    id: 146,
    gameTeamId: 21,
    playerId: 120,
    jerseyNumber: '5'
  }),
  build(GamePlayer, {
    id: 147,
    gameTeamId: 21,
    playerId: 112,
    jerseyNumber: '8'
  }),
  build(GamePlayer, {
    id: 148,
    gameTeamId: 21,
    playerId: 114,
    jerseyNumber: '9'
  }),
  build(GamePlayer, {
    id: 149,
    gameTeamId: 22,
    playerId: 124,
    jerseyNumber: '0'
  }),
  build(GamePlayer, {
    id: 150,
    gameTeamId: 22,
    playerId: 127,
    jerseyNumber: '1'
  }),
  build(GamePlayer, {
    id: 151,
    gameTeamId: 22,
    playerId: 125,
    jerseyNumber: '2'
  }),
  build(GamePlayer, {
    id: 152,
    gameTeamId: 22,
    playerId: 158,
    jerseyNumber: '3'
  }),
  build(GamePlayer, {
    id: 153,
    gameTeamId: 22,
    playerId: 159,
    jerseyNumber: '4'
  }),
  build(GamePlayer, {
    id: 154,
    gameTeamId: 22,
    playerId: 129,
    jerseyNumber: '5'
  }),
  build(GamePlayer, {
    id: 155,
    gameTeamId: 22,
    playerId: 123,
    jerseyNumber: '6'
  }),
  build(GamePlayer, {
    id: 156,
    gameTeamId: 22,
    playerId: 126,
    jerseyNumber: '7'
  }),
  build(GamePlayer, {
    id: 157,
    gameTeamId: 22,
    playerId: 122,
    jerseyNumber: '8'
  }),
  build(GamePlayer, {
    id: 158,
    gameTeamId: 22,
    playerId: 124,
    jerseyNumber: '9'
  }),
  build(GamePlayer, {
    id: 159,
    gameTeamId: 23,
    playerId: 107,
    jerseyNumber: '0'
  }),
  build(GamePlayer, {
    id: 160,
    gameTeamId: 23,
    playerId: 109,
    jerseyNumber: '1'
  }),
  build(GamePlayer, {
    id: 161,
    gameTeamId: 23,
    playerId: 105,
    jerseyNumber: '3'
  }),
  build(GamePlayer, {
    id: 162,
    gameTeamId: 23,
    playerId: 111,
    jerseyNumber: '4'
  }),
  build(GamePlayer, {
    id: 163,
    gameTeamId: 23,
    playerId: 104,
    jerseyNumber: '5'
  }),
  build(GamePlayer, { id: 164, gameTeamId: 23, playerId: 80, jerseyNumber: '6' }),
  build(GamePlayer, {
    id: 165,
    gameTeamId: 23,
    playerId: 106,
    jerseyNumber: '8'
  }),
  build(GamePlayer, {
    id: 166,
    gameTeamId: 24,
    playerId: 135,
    jerseyNumber: '00'
  }),
  build(GamePlayer, {
    id: 167,
    gameTeamId: 24,
    playerId: 130,
    jerseyNumber: '2'
  }),
  build(GamePlayer, {
    id: 168,
    gameTeamId: 24,
    playerId: 161,
    jerseyNumber: '2'
  }),
  build(GamePlayer, {
    id: 169,
    gameTeamId: 24,
    playerId: 136,
    jerseyNumber: '3'
  }),
  build(GamePlayer, {
    id: 170,
    gameTeamId: 24,
    playerId: 131,
    jerseyNumber: '7'
  }),
  build(GamePlayer, { id: 171, gameTeamId: 24, playerId: 132, jerseyNumber: '8' })
];

export const STATS = [
  build(Stat, { gamePlayerId: 1, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 1, statCategoryId: 2, total: 9 }),
  build(Stat, { gamePlayerId: 1, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 1, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 1, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 2, statCategoryId: 1, total: 11 }),
  build(Stat, { gamePlayerId: 2, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 2, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 2, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 2, statCategoryId: 5, total: 5 }),
  build(Stat, { gamePlayerId: 3, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 3, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 3, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 3, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 3, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 4, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 4, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 4, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 4, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 4, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 5, statCategoryId: 1, total: 6 }),
  build(Stat, { gamePlayerId: 5, statCategoryId: 2, total: 10 }),
  build(Stat, { gamePlayerId: 5, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 5, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 5, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 6, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 6, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 6, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 6, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 6, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 7, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 7, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 7, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 7, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 7, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 8, statCategoryId: 1, total: 8 }),
  build(Stat, { gamePlayerId: 8, statCategoryId: 2, total: 7 }),
  build(Stat, { gamePlayerId: 8, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 8, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 8, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 9, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 9, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 9, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 9, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 9, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 10, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 10, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 10, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 10, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 10, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 11, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 11, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 11, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 11, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 11, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 12, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 12, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 12, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 12, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 12, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 13, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 13, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 13, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 13, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 13, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 14, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 14, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 14, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 14, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 14, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 15, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 15, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 15, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 15, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 15, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 16, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 16, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 16, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 16, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 16, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 17, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 17, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 17, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 17, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 17, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 18, statCategoryId: 1, total: 6 }),
  build(Stat, { gamePlayerId: 18, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 18, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 18, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 18, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 19, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 19, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 19, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 19, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 19, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 20, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 20, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 20, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 20, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 20, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 21, statCategoryId: 1, total: 7 }),
  build(Stat, { gamePlayerId: 21, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 21, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 21, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 21, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 22, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 22, statCategoryId: 2, total: 7 }),
  build(Stat, { gamePlayerId: 22, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 22, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 22, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 23, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 23, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 23, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 23, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 23, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 24, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 24, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 24, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 24, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 24, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 25, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 25, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 25, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 25, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 25, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 26, statCategoryId: 1, total: 1 }),
  build(Stat, { gamePlayerId: 26, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 26, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 26, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 26, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 27, statCategoryId: 1, total: 9 }),
  build(Stat, { gamePlayerId: 27, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 27, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 27, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 27, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 28, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 28, statCategoryId: 2, total: 12 }),
  build(Stat, { gamePlayerId: 28, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 28, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 28, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 29, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 29, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 29, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 29, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 29, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 30, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 30, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 30, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 30, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 30, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 31, statCategoryId: 1, total: 5 }),
  build(Stat, { gamePlayerId: 31, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 31, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 31, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 31, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 32, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 32, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 32, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 32, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 32, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 33, statCategoryId: 1, total: 5 }),
  build(Stat, { gamePlayerId: 33, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 33, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 33, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 33, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 34, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 34, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 34, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 34, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 34, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 35, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 35, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 35, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 35, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 35, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 36, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 36, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 36, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 36, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 36, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 37, statCategoryId: 1, total: 12 }),
  build(Stat, { gamePlayerId: 37, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 37, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 37, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 37, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 38, statCategoryId: 1, total: 7 }),
  build(Stat, { gamePlayerId: 38, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 38, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 38, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 38, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 39, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 39, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 39, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 39, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 39, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 40, statCategoryId: 1, total: 8 }),
  build(Stat, { gamePlayerId: 40, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 40, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 40, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 40, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 41, statCategoryId: 1, total: 8 }),
  build(Stat, { gamePlayerId: 41, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 41, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 41, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 41, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 42, statCategoryId: 1, total: 19 }),
  build(Stat, { gamePlayerId: 42, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 42, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 42, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 42, statCategoryId: 5, total: 9 }),
  build(Stat, { gamePlayerId: 43, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 43, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 43, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 43, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 43, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 44, statCategoryId: 1, total: 8 }),
  build(Stat, { gamePlayerId: 44, statCategoryId: 2, total: 14 }),
  build(Stat, { gamePlayerId: 44, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 44, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 44, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 45, statCategoryId: 1, total: 6 }),
  build(Stat, { gamePlayerId: 45, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 45, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 45, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 45, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 46, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 46, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 46, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 46, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 46, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 47, statCategoryId: 1, total: 5 }),
  build(Stat, { gamePlayerId: 47, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 47, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 47, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 47, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 48, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 48, statCategoryId: 2, total: 7 }),
  build(Stat, { gamePlayerId: 48, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 48, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 48, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 49, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 49, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 49, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 49, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 49, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 50, statCategoryId: 1, total: 6 }),
  build(Stat, { gamePlayerId: 50, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 50, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 50, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 50, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 51, statCategoryId: 1, total: 9 }),
  build(Stat, { gamePlayerId: 51, statCategoryId: 2, total: 12 }),
  build(Stat, { gamePlayerId: 51, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 51, statCategoryId: 4, total: 2 }),
  build(Stat, { gamePlayerId: 51, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 52, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 52, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 52, statCategoryId: 3, total: 3 }),
  build(Stat, { gamePlayerId: 52, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 52, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 53, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 53, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 53, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 53, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 53, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 54, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 54, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 54, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 54, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 54, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 55, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 55, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 55, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 55, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 55, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 56, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 56, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 56, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 56, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 56, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 57, statCategoryId: 1, total: 3 }),
  build(Stat, { gamePlayerId: 57, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 57, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 57, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 57, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 58, statCategoryId: 1, total: 1 }),
  build(Stat, { gamePlayerId: 58, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 58, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 58, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 58, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 59, statCategoryId: 1, total: 3 }),
  build(Stat, { gamePlayerId: 59, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 59, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 59, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 59, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 60, statCategoryId: 1, total: 12 }),
  build(Stat, { gamePlayerId: 60, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 60, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 60, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 60, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 61, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 61, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 61, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 61, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 61, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 62, statCategoryId: 1, total: 16 }),
  build(Stat, { gamePlayerId: 62, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 62, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 62, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 62, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 63, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 63, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 63, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 63, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 63, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 64, statCategoryId: 1, total: 19 }),
  build(Stat, { gamePlayerId: 64, statCategoryId: 2, total: 8 }),
  build(Stat, { gamePlayerId: 64, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 64, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 64, statCategoryId: 5, total: 6 }),
  build(Stat, { gamePlayerId: 65, statCategoryId: 1, total: 6 }),
  build(Stat, { gamePlayerId: 65, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 65, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 65, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 65, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 66, statCategoryId: 1, total: 11 }),
  build(Stat, { gamePlayerId: 66, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 66, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 66, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 66, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 67, statCategoryId: 1, total: 6 }),
  build(Stat, { gamePlayerId: 67, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 67, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 67, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 67, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 68, statCategoryId: 1, total: 15 }),
  build(Stat, { gamePlayerId: 68, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 68, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 68, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 68, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 69, statCategoryId: 1, total: 16 }),
  build(Stat, { gamePlayerId: 69, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 69, statCategoryId: 3, total: 4 }),
  build(Stat, { gamePlayerId: 69, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 69, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 70, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 70, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 70, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 70, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 70, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 71, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 71, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 71, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 71, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 71, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 72, statCategoryId: 1, total: 6 }),
  build(Stat, { gamePlayerId: 72, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 72, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 72, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 72, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 73, statCategoryId: 1, total: 6 }),
  build(Stat, { gamePlayerId: 73, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 73, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 73, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 73, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 74, statCategoryId: 1, total: 25 }),
  build(Stat, { gamePlayerId: 74, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 74, statCategoryId: 3, total: 8 }),
  build(Stat, { gamePlayerId: 74, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 74, statCategoryId: 5, total: 4 }),
  build(Stat, { gamePlayerId: 75, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 75, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 75, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 75, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 75, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 76, statCategoryId: 1, total: 15 }),
  build(Stat, { gamePlayerId: 76, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 76, statCategoryId: 3, total: 5 }),
  build(Stat, { gamePlayerId: 76, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 76, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 77, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 77, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 77, statCategoryId: 3, total: 3 }),
  build(Stat, { gamePlayerId: 77, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 77, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 78, statCategoryId: 1, total: 31 }),
  build(Stat, { gamePlayerId: 78, statCategoryId: 2, total: 10 }),
  build(Stat, { gamePlayerId: 78, statCategoryId: 3, total: 3 }),
  build(Stat, { gamePlayerId: 78, statCategoryId: 4, total: 3 }),
  build(Stat, { gamePlayerId: 78, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 79, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 79, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 79, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 79, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 79, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 80, statCategoryId: 1, total: 10 }),
  build(Stat, { gamePlayerId: 80, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 80, statCategoryId: 3, total: 8 }),
  build(Stat, { gamePlayerId: 80, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 80, statCategoryId: 5, total: 4 }),
  build(Stat, { gamePlayerId: 81, statCategoryId: 1, total: 3 }),
  build(Stat, { gamePlayerId: 81, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 81, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 81, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 81, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 82, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 82, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 82, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 82, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 82, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 83, statCategoryId: 1, total: 12 }),
  build(Stat, { gamePlayerId: 83, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 83, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 83, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 83, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 84, statCategoryId: 1, total: 29 }),
  build(Stat, { gamePlayerId: 84, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 84, statCategoryId: 3, total: 4 }),
  build(Stat, { gamePlayerId: 84, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 84, statCategoryId: 5, total: 4 }),
  build(Stat, { gamePlayerId: 85, statCategoryId: 1, total: 5 }),
  build(Stat, { gamePlayerId: 85, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 85, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 85, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 85, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 86, statCategoryId: 1, total: 10 }),
  build(Stat, { gamePlayerId: 86, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 86, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 86, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 86, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 87, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 87, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 87, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 87, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 87, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 88, statCategoryId: 1, total: 1 }),
  build(Stat, { gamePlayerId: 88, statCategoryId: 2, total: 8 }),
  build(Stat, { gamePlayerId: 88, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 88, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 88, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 89, statCategoryId: 1, total: 3 }),
  build(Stat, { gamePlayerId: 89, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 89, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 89, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 89, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 90, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 90, statCategoryId: 2, total: 7 }),
  build(Stat, { gamePlayerId: 90, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 90, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 90, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 91, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 91, statCategoryId: 2, total: 8 }),
  build(Stat, { gamePlayerId: 91, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 91, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 91, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 92, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 92, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 92, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 92, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 92, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 93, statCategoryId: 1, total: 20 }),
  build(Stat, { gamePlayerId: 93, statCategoryId: 2, total: 18 }),
  build(Stat, { gamePlayerId: 93, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 93, statCategoryId: 4, total: 6 }),
  build(Stat, { gamePlayerId: 93, statCategoryId: 5, total: 9 }),
  build(Stat, { gamePlayerId: 94, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 94, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 94, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 94, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 94, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 95, statCategoryId: 1, total: 6 }),
  build(Stat, { gamePlayerId: 95, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 95, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 95, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 95, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 96, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 96, statCategoryId: 2, total: 8 }),
  build(Stat, { gamePlayerId: 96, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 96, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 96, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 97, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 97, statCategoryId: 2, total: 8 }),
  build(Stat, { gamePlayerId: 97, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 97, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 97, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 98, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 98, statCategoryId: 2, total: 7 }),
  build(Stat, { gamePlayerId: 98, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 98, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 98, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 99, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 99, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 99, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 99, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 99, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 100, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 100, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 100, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 100, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 100, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 101, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 101, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 101, statCategoryId: 3, total: 3 }),
  build(Stat, { gamePlayerId: 101, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 101, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 102, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 102, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 102, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 102, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 102, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 103, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 103, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 103, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 103, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 103, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 104, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 104, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 104, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 104, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 104, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 105, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 105, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 105, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 105, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 105, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 106, statCategoryId: 1, total: 7 }),
  build(Stat, { gamePlayerId: 106, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 106, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 106, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 106, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 107, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 107, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 107, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 107, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 107, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 108, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 108, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 108, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 108, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 108, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 109, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 109, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 109, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 109, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 109, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 110, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 110, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 110, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 110, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 110, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 111, statCategoryId: 1, total: 10 }),
  build(Stat, { gamePlayerId: 111, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 111, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 111, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 111, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 112, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 112, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 112, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 112, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 112, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 113, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 113, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 113, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 113, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 113, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 114, statCategoryId: 1, total: 8 }),
  build(Stat, { gamePlayerId: 114, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 114, statCategoryId: 3, total: 4 }),
  build(Stat, { gamePlayerId: 114, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 114, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 115, statCategoryId: 1, total: 10 }),
  build(Stat, { gamePlayerId: 115, statCategoryId: 2, total: 22 }),
  build(Stat, { gamePlayerId: 115, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 115, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 115, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 116, statCategoryId: 1, total: 12 }),
  build(Stat, { gamePlayerId: 116, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 116, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 116, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 116, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 117, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 117, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 117, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 117, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 117, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 118, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 118, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 118, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 118, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 118, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 119, statCategoryId: 1, total: 13 }),
  build(Stat, { gamePlayerId: 119, statCategoryId: 2, total: 16 }),
  build(Stat, { gamePlayerId: 119, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 119, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 119, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 120, statCategoryId: 1, total: 3 }),
  build(Stat, { gamePlayerId: 120, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 120, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 120, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 120, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 121, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 121, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 121, statCategoryId: 3, total: 4 }),
  build(Stat, { gamePlayerId: 121, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 121, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 122, statCategoryId: 1, total: 12 }),
  build(Stat, { gamePlayerId: 122, statCategoryId: 2, total: 9 }),
  build(Stat, { gamePlayerId: 122, statCategoryId: 3, total: 3 }),
  build(Stat, { gamePlayerId: 122, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 122, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 123, statCategoryId: 1, total: 10 }),
  build(Stat, { gamePlayerId: 123, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 123, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 123, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 123, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 124, statCategoryId: 1, total: 15 }),
  build(Stat, { gamePlayerId: 124, statCategoryId: 2, total: 12 }),
  build(Stat, { gamePlayerId: 124, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 124, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 124, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 125, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 125, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 125, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 125, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 125, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 126, statCategoryId: 1, total: 19 }),
  build(Stat, { gamePlayerId: 126, statCategoryId: 2, total: 8 }),
  build(Stat, { gamePlayerId: 126, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 126, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 126, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 127, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 127, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 127, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 127, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 127, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 128, statCategoryId: 1, total: 3 }),
  build(Stat, { gamePlayerId: 128, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 128, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 128, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 128, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 129, statCategoryId: 1, total: 6 }),
  build(Stat, { gamePlayerId: 129, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 129, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 129, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 129, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 130, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 130, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 130, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 130, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 130, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 131, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 131, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 131, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 131, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 131, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 132, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 132, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 132, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 132, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 132, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 133, statCategoryId: 1, total: 12 }),
  build(Stat, { gamePlayerId: 133, statCategoryId: 2, total: 11 }),
  build(Stat, { gamePlayerId: 133, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 133, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 133, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 134, statCategoryId: 1, total: 7 }),
  build(Stat, { gamePlayerId: 134, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 134, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 134, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 134, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 135, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 135, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 135, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 135, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 135, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 136, statCategoryId: 1, total: 12 }),
  build(Stat, { gamePlayerId: 136, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 136, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 136, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 136, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 137, statCategoryId: 1, total: 1 }),
  build(Stat, { gamePlayerId: 137, statCategoryId: 2, total: 7 }),
  build(Stat, { gamePlayerId: 137, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 137, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 137, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 138, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 138, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 138, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 138, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 138, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 139, statCategoryId: 1, total: 1 }),
  build(Stat, { gamePlayerId: 139, statCategoryId: 2, total: 7 }),
  build(Stat, { gamePlayerId: 139, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 139, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 139, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 140, statCategoryId: 1, total: 7 }),
  build(Stat, { gamePlayerId: 140, statCategoryId: 2, total: 8 }),
  build(Stat, { gamePlayerId: 140, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 140, statCategoryId: 4, total: 3 }),
  build(Stat, { gamePlayerId: 140, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 141, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 141, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 141, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 141, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 141, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 142, statCategoryId: 1, total: 47 }),
  build(Stat, { gamePlayerId: 142, statCategoryId: 2, total: 8 }),
  build(Stat, { gamePlayerId: 142, statCategoryId: 3, total: 6 }),
  build(Stat, { gamePlayerId: 142, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 142, statCategoryId: 5, total: 4 }),
  build(Stat, { gamePlayerId: 143, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 143, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 143, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 143, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 143, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 144, statCategoryId: 1, total: 36 }),
  build(Stat, { gamePlayerId: 144, statCategoryId: 2, total: 13 }),
  build(Stat, { gamePlayerId: 144, statCategoryId: 3, total: 4 }),
  build(Stat, { gamePlayerId: 144, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 144, statCategoryId: 5, total: 9 }),
  build(Stat, { gamePlayerId: 145, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 145, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 145, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 145, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 145, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 146, statCategoryId: 1, total: 15 }),
  build(Stat, { gamePlayerId: 146, statCategoryId: 2, total: 9 }),
  build(Stat, { gamePlayerId: 146, statCategoryId: 3, total: 5 }),
  build(Stat, { gamePlayerId: 146, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 146, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 147, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 147, statCategoryId: 2, total: 8 }),
  build(Stat, { gamePlayerId: 147, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 147, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 147, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 148, statCategoryId: 1, total: 4 }),
  build(Stat, { gamePlayerId: 148, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 148, statCategoryId: 3, total: 3 }),
  build(Stat, { gamePlayerId: 148, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 148, statCategoryId: 5, total: 5 }),
  build(Stat, { gamePlayerId: 149, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 149, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 149, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 149, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 149, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 150, statCategoryId: 1, total: 11 }),
  build(Stat, { gamePlayerId: 150, statCategoryId: 2, total: 6 }),
  build(Stat, { gamePlayerId: 150, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 150, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 150, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 151, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 151, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 151, statCategoryId: 3, total: 3 }),
  build(Stat, { gamePlayerId: 151, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 151, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 152, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 152, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 152, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 152, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 152, statCategoryId: 5, total: 4 }),
  build(Stat, { gamePlayerId: 153, statCategoryId: 1, total: 25 }),
  build(Stat, { gamePlayerId: 153, statCategoryId: 2, total: 14 }),
  build(Stat, { gamePlayerId: 153, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 153, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 153, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 154, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 154, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 154, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 154, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 154, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 155, statCategoryId: 1, total: 7 }),
  build(Stat, { gamePlayerId: 155, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 155, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 155, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 155, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 156, statCategoryId: 1, total: 3 }),
  build(Stat, { gamePlayerId: 156, statCategoryId: 2, total: 8 }),
  build(Stat, { gamePlayerId: 156, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 156, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 156, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 157, statCategoryId: 1, total: 17 }),
  build(Stat, { gamePlayerId: 157, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 157, statCategoryId: 3, total: 7 }),
  build(Stat, { gamePlayerId: 157, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 157, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 158, statCategoryId: 1, total: 7 }),
  build(Stat, { gamePlayerId: 158, statCategoryId: 2, total: 15 }),
  build(Stat, { gamePlayerId: 158, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 158, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 158, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 159, statCategoryId: 1, total: 12 }),
  build(Stat, { gamePlayerId: 159, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 159, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 159, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 159, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 160, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 160, statCategoryId: 2, total: 0 }),
  build(Stat, { gamePlayerId: 160, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 160, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 160, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 161, statCategoryId: 1, total: 13 }),
  build(Stat, { gamePlayerId: 161, statCategoryId: 2, total: 10 }),
  build(Stat, { gamePlayerId: 161, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 161, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 161, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 162, statCategoryId: 1, total: 8 }),
  build(Stat, { gamePlayerId: 162, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 162, statCategoryId: 3, total: 9 }),
  build(Stat, { gamePlayerId: 162, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 162, statCategoryId: 5, total: 5 }),
  build(Stat, { gamePlayerId: 163, statCategoryId: 1, total: 13 }),
  build(Stat, { gamePlayerId: 163, statCategoryId: 2, total: 9 }),
  build(Stat, { gamePlayerId: 163, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 163, statCategoryId: 4, total: 2 }),
  build(Stat, { gamePlayerId: 163, statCategoryId: 5, total: 5 }),
  build(Stat, { gamePlayerId: 164, statCategoryId: 1, total: 9 }),
  build(Stat, { gamePlayerId: 164, statCategoryId: 2, total: 5 }),
  build(Stat, { gamePlayerId: 164, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 164, statCategoryId: 4, total: 2 }),
  build(Stat, { gamePlayerId: 164, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 165, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 165, statCategoryId: 2, total: 9 }),
  build(Stat, { gamePlayerId: 165, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 165, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 165, statCategoryId: 5, total: 1 }),
  build(Stat, { gamePlayerId: 166, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 166, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 166, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 166, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 166, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 167, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 167, statCategoryId: 2, total: 3 }),
  build(Stat, { gamePlayerId: 167, statCategoryId: 3, total: 4 }),
  build(Stat, { gamePlayerId: 167, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 167, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 168, statCategoryId: 1, total: 0 }),
  build(Stat, { gamePlayerId: 168, statCategoryId: 2, total: 1 }),
  build(Stat, { gamePlayerId: 168, statCategoryId: 3, total: 1 }),
  build(Stat, { gamePlayerId: 168, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 168, statCategoryId: 5, total: 2 }),
  build(Stat, { gamePlayerId: 169, statCategoryId: 1, total: 5 }),
  build(Stat, { gamePlayerId: 169, statCategoryId: 2, total: 2 }),
  build(Stat, { gamePlayerId: 169, statCategoryId: 3, total: 2 }),
  build(Stat, { gamePlayerId: 169, statCategoryId: 4, total: 0 }),
  build(Stat, { gamePlayerId: 169, statCategoryId: 5, total: 0 }),
  build(Stat, { gamePlayerId: 170, statCategoryId: 1, total: 9 }),
  build(Stat, { gamePlayerId: 170, statCategoryId: 2, total: 4 }),
  build(Stat, { gamePlayerId: 170, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 170, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 170, statCategoryId: 5, total: 3 }),
  build(Stat, { gamePlayerId: 171, statCategoryId: 1, total: 2 }),
  build(Stat, { gamePlayerId: 171, statCategoryId: 2, total: 7 }),
  build(Stat, { gamePlayerId: 171, statCategoryId: 3, total: 0 }),
  build(Stat, { gamePlayerId: 171, statCategoryId: 4, total: 1 }),
  build(Stat, { gamePlayerId: 171, statCategoryId: 5, total: 0 })
];

export const INITIAL_STATE = {
  players: build(Players, { items: PLAYERS }),
  teams: build(Teams, { items: TEAMS }),
  leagues: build(Leagues, { items: LEAGUES }),
  locations: build(Locations, { items: LOCATIONS }),
  games: build(Games, { items: GAMES }),
  gameTeams: build(GameTeams, { items: GAME_TEAMS }),
  gamePlayers: build(GamePlayers, { items: GAME_PLAYERS }),
  statCategories: build(StatCategories, { items: STAT_CATEGORIES }),
  stats: build(Stats, { items: STATS }),
  teamStats: build(TeamStats, { items: TEAM_STATS })
};
